### ISSUE TITLE
Warning: apt-key output should not be parsed

### ISSUE THREAD

**Issue by dpprdan** [ankane/setup-postgres#6]
The action [throws a warning](https://github.com/ankane/setup-postgres/runs/4121903226?check_suite_focus=true#step:3:8) on Ubuntu:

```bash
wget --quiet -O - postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
```

The warning doesn't show up in the [action summary of this repo](https://github.com/ankane/setup-postgres/actions/runs/1427411732) for some reason, but it does [elsewhere](https://github.com/r-dbi/RPostgres/actions/runs/1427963723), see [details](https://github.com/r-dbi/RPostgres/runs/4123356787?check_suite_focus=true#step:13:14).

[More info](https://askubuntu.com/a/1236659) on the warning.

**Comment by ankane** [comment]
Fixed in the commit above.
