### ISSUE TITLE
Move to Node 16

### ISSUE THREAD

**Issue by krlmlr** [ankane/setup-postgres#7]
GitHub Actions suggests that Node 12 will be deprecated by mid-2023: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. I don't know how much we need to change, but I'm relying on the following actions:

- [ ] This repo
- [ ] https://github.com/ankane/setup-sqlserver
- [ ] https://github.com/ankane/setup-mariadb
- [ ] https://github.com/ankane/setup-mysql

What's the best way to move forward?

**Comment by ankane** [comment]
Hey @krlmlr, they should all be on Node 16 now (were updated a few days ago).

**Comment by krlmlr** [comment]
Thanks. I'll double-check the tags/branches my workflows are using.
